#!/bin/bash
PATH=/usr/local/share/python:$PATH
export PATH

#NVM path Nodejs Version Manager
export NVM_DIR=~/.nvm
  . $(brew --prefix nvm)/nvm.sh

#Android HOME and bin
export ANDROID_HOME=/usr/local/opt/android-sdk
export PATH="$ANDROID_HOME/bin:$PATH"

#alias for cnpm(taobao.org) Nodejs Package Manager
alias cnpm="npm --registry=https://registry.npm.taobao.org \
  --cache=$HOME/.npm/.cache/cnpm \
  --disturl=https://npm.taobao.org/dist \
  --userconfig=$HOME/.cnpmrc"

# RVM - Ruby Version Manager
# Load RVM into a shell session *as a function*
# Add RVM to PATH for scripting
# for brew path
export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*


